# Generated by Django 5.1.3 on 2025-06-01 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('score', models.FloatField(default=0.0)),
                ('games_as_white', models.IntegerField(default=0)),
                ('games_as_black', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app_simple_tournament.tournament')),
            ],
            options={
                'ordering': ['-score', 'name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('result', models.CharField(choices=[('W', 'White Wins'), ('B', 'Black Wins'), ('D', 'Draw'), ('BYE', 'Bye'), ('N', 'Not Played')], default='N', max_length=3)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('player_black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_black', to='app_simple_tournament.player')),
                ('player_white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_white', to='app_simple_tournament.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app_simple_tournament.tournament')),
            ],
            options={
                'ordering': ['round_number', 'match_date'],
                'unique_together': {('tournament', 'round_number', 'player_white', 'player_black')},
            },
        ),
        migrations.CreateModel(
            name='AllMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('matches', models.ManyToManyField(blank=True, related_name='collections', to='app_simple_tournament.match')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_collections', to='app_simple_tournament.tournament')),
            ],
        ),
    ]
