# Generated by Django 5.1.3 on 2025-03-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_simple_tournament', '0002_tournament_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
