# Generated by Django 5.1.3 on 2025-05-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_simple_tournament', '0004_tournament_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-rating', 'name']},
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('tournament', 'name')},
        ),
    ]
